// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.6
// source: proto/internal.proto

package orchestrator

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_internal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_internal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_internal_proto_rawDescGZIP(), []int{0}
}

type TaskToSend struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PairId        int32                  `protobuf:"varint,1,opt,name=PairId,proto3" json:"PairId,omitempty"`
	Arg1          int64                  `protobuf:"varint,2,opt,name=Arg1,proto3" json:"Arg1,omitempty"`
	Arg2          int64                  `protobuf:"varint,3,opt,name=Arg2,proto3" json:"Arg2,omitempty"`
	Operation     string                 `protobuf:"bytes,4,opt,name=Operation,proto3" json:"Operation,omitempty"`
	OperationTime string                 `protobuf:"bytes,5,opt,name=OperationTime,proto3" json:"OperationTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskToSend) Reset() {
	*x = TaskToSend{}
	mi := &file_proto_internal_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskToSend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskToSend) ProtoMessage() {}

func (x *TaskToSend) ProtoReflect() protoreflect.Message {
	mi := &file_proto_internal_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskToSend.ProtoReflect.Descriptor instead.
func (*TaskToSend) Descriptor() ([]byte, []int) {
	return file_proto_internal_proto_rawDescGZIP(), []int{1}
}

func (x *TaskToSend) GetPairId() int32 {
	if x != nil {
		return x.PairId
	}
	return 0
}

func (x *TaskToSend) GetArg1() int64 {
	if x != nil {
		return x.Arg1
	}
	return 0
}

func (x *TaskToSend) GetArg2() int64 {
	if x != nil {
		return x.Arg2
	}
	return 0
}

func (x *TaskToSend) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *TaskToSend) GetOperationTime() string {
	if x != nil {
		return x.OperationTime
	}
	return ""
}

type TaskResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PairId        int32                  `protobuf:"varint,1,opt,name=PairId,proto3" json:"PairId,omitempty"`
	Result        int64                  `protobuf:"varint,2,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskResult) Reset() {
	*x = TaskResult{}
	mi := &file_proto_internal_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResult) ProtoMessage() {}

func (x *TaskResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_internal_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResult.ProtoReflect.Descriptor instead.
func (*TaskResult) Descriptor() ([]byte, []int) {
	return file_proto_internal_proto_rawDescGZIP(), []int{2}
}

func (x *TaskResult) GetPairId() int32 {
	if x != nil {
		return x.PairId
	}
	return 0
}

func (x *TaskResult) GetResult() int64 {
	if x != nil {
		return x.Result
	}
	return 0
}

var File_proto_internal_proto protoreflect.FileDescriptor

const file_proto_internal_proto_rawDesc = "" +
	"\n" +
	"\x14proto/internal.proto\x12\x04main\"\a\n" +
	"\x05Empty\"\x90\x01\n" +
	"\n" +
	"TaskToSend\x12\x16\n" +
	"\x06PairId\x18\x01 \x01(\x05R\x06PairId\x12\x12\n" +
	"\x04Arg1\x18\x02 \x01(\x03R\x04Arg1\x12\x12\n" +
	"\x04Arg2\x18\x03 \x01(\x03R\x04Arg2\x12\x1c\n" +
	"\tOperation\x18\x04 \x01(\tR\tOperation\x12$\n" +
	"\rOperationTime\x18\x05 \x01(\tR\rOperationTime\"<\n" +
	"\n" +
	"TaskResult\x12\x16\n" +
	"\x06PairId\x18\x01 \x01(\x05R\x06PairId\x12\x16\n" +
	"\x06result\x18\x02 \x01(\x03R\x06result2b\n" +
	"\vTaskService\x12(\n" +
	"\aGetTask\x12\v.main.Empty\x1a\x10.main.TaskToSend\x12)\n" +
	"\bSendTask\x12\x10.main.TaskResult\x1a\v.main.EmptyB8Z6github.com/Debianov/calc-ya-go-24/backend/orchestratorb\x06proto3"

var (
	file_proto_internal_proto_rawDescOnce sync.Once
	file_proto_internal_proto_rawDescData []byte
)

func file_proto_internal_proto_rawDescGZIP() []byte {
	file_proto_internal_proto_rawDescOnce.Do(func() {
		file_proto_internal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_internal_proto_rawDesc), len(file_proto_internal_proto_rawDesc)))
	})
	return file_proto_internal_proto_rawDescData
}

var file_proto_internal_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_internal_proto_goTypes = []any{
	(*Empty)(nil),      // 0: main.Empty
	(*TaskToSend)(nil), // 1: main.TaskToSend
	(*TaskResult)(nil), // 2: main.TaskResult
}
var file_proto_internal_proto_depIdxs = []int32{
	0, // 0: main.TaskService.GetTask:input_type -> main.Empty
	2, // 1: main.TaskService.SendTask:input_type -> main.TaskResult
	1, // 2: main.TaskService.GetTask:output_type -> main.TaskToSend
	0, // 3: main.TaskService.SendTask:output_type -> main.Empty
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_internal_proto_init() }
func file_proto_internal_proto_init() {
	if File_proto_internal_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_internal_proto_rawDesc), len(file_proto_internal_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_internal_proto_goTypes,
		DependencyIndexes: file_proto_internal_proto_depIdxs,
		MessageInfos:      file_proto_internal_proto_msgTypes,
	}.Build()
	File_proto_internal_proto = out.File
	file_proto_internal_proto_goTypes = nil
	file_proto_internal_proto_depIdxs = nil
}
